// ============================================================
// REAL SCHOLARSHIP DATA — verified from official/authoritative sources.
// Every field is either sourced directly or explicitly marked "Needs verification."
// No amounts, deadlines, eligibility rules, or URLs are invented.
// lastChecked reflects the date this entry was researched: 2026-08-16.
// Deadlines and amounts change — students should always confirm on the
// official application page (applyUrl) before relying on any figure here.
// ============================================================

const SCHOLARSHIPS = [
  {
    id: 'coca-cola-scholars',
    name: 'Coca-Cola Scholars Program',
    provider: 'Coca-Cola Scholars Foundation',
    amount: 20000,
    amountDisplay: '$20,000',
    amountNote: null,
    deadline: 'Sep 30, 2026',
    deadlineNote: '5:00 PM Eastern. Application opens Aug 3, 2026.',
    deadlineVerified: true,
    level: ["High school senior (entering Bachelor's/Associate)"],
    field: 'Any field — achievement-based, not major-specific',
    citizenship: ['U.S. citizen, U.S. national, U.S. permanent resident, refugee, asylee, Cuban-Haitian entrant, or humanitarian parolee'],
    locationNote: 'Must attend high school in one of the 50 U.S. states, D.C., Puerto Rico, or select DoD schools. Students at American/expat schools abroad are not eligible.',
    gpaMin: 3.0,
    gpaNote: 'Minimum 3.0 unweighted GPA',
    needBased: false,
    meritBased: true,
    requirements: ['Online application', 'Eligibility quiz', 'No essay, transcript, or recommendation required at initial stage (only if named semifinalist)'],
    why: 'Achievement-based, not need-based — evaluates leadership, academics, and service. No essay required to start.',
    applyUrl: 'https://www.coca-colascholarsfoundation.org/apply/',
    sourceUrl: 'https://www.coca-colascholarsfoundation.org/about/faq',
    sourceUrls: [
      'https://www.coca-colascholarsfoundation.org/apply/',
      'https://www.coca-colascholarsfoundation.org/about/faq'
    ],
    lastChecked: '2026-08-16'
  },
  {
    id: 'dell-scholars',
    name: 'Dell Scholars Program',
    provider: 'Michael & Susan Dell Foundation',
    amount: 20000,
    amountDisplay: '$20,000',
    amountNote: 'Flexible award — plus a laptop, textbook credits, and emergency funds. Can be used for tuition, housing, grad school, study abroad, or loan repayment.',
    deadline: 'Feb 15, 2026 (closed)',
    deadlineNote: 'Confirmed via official site: 2025-26 cycle — Applications opened Dec 15, 2025, closed Feb 15, 2026. The 2026-27 cycle dates were not yet posted as of this check.',
    deadlineVerified: true,
    deadlineStatus: 'closed_for_cycle',
    level: ["High school senior (entering Bachelor's, full-time)"],
    field: 'All majors',
    citizenship: ['No residency/citizenship restriction stated on official eligibility page'],
    locationNote: 'Must enroll full-time at an accredited four-year U.S. college or university right after high school.',
    gpaMin: 2.4,
    gpaNote: 'Minimum 2.4 GPA',
    needBased: true,
    meritBased: false,
    requirements: ['Approved college-readiness program participation (grades 11-12)', 'Pell Grant eligibility', 'FAFSA Submission Summary (if finalist)', 'Recommendation letter (if semifinalist)'],
    why: 'Need-based, not GPA-competitive — built for students who\'ve overcome obstacles and completed an approved college-readiness program.',
    applyUrl: 'https://www.dellscholars.org/students/',
    sourceUrl: 'https://www.dellscholars.org/students/',
    sourceUrls: ['https://www.dellscholars.org/students/'],
    lastChecked: '2026-08-16'
  },
  {
    id: 'questbridge-match',
    name: 'QuestBridge National College Match',
    provider: 'QuestBridge',
    amount: null,
    amountDisplay: 'Full four-year scholarship',
    amountNote: 'Full cost of attendance at a QuestBridge partner college — not a fixed dollar figure; varies by school\'s cost of attendance and aid policy.',
    deadline: 'Oct 1, 2026',
    deadlineNote: '11:59 PM Pacific Time. Rankings/Match Agreement due Oct 15, 2026. Match Day Dec 1, 2026.',
    deadlineVerified: true,
    level: ["High school senior (entering Bachelor's)"],
    field: 'Any field',
    citizenship: ['U.S. citizens and permanent residents', 'International students living outside the U.S. are NOT eligible'],
    locationNote: 'Must be currently attending high school in the U.S. and planning to attend college the fall after senior year.',
    gpaMin: null,
    gpaNote: 'No fixed GPA cutoff stated — QuestBridge does not publish absolute GPA/test-score criteria.',
    needBased: true,
    meritBased: true,
    requirements: ['Free online application', 'Multiple essays', 'Teacher recommendations', 'Transcript', 'Rank up to 15 college partners', 'Binding Match commitment if matched'],
    why: 'For high-achieving students from low-income backgrounds — connects you to 55+ partner colleges for full-ride early admission.',
    applyUrl: 'https://www.questbridge.org/apply-to-college/programs/national-college-match/apply',
    sourceUrl: 'https://www.questbridge.org/apply-to-college/programs/national-college-match/apply/dates-and-deadlines',
    sourceUrls: [
      'https://www.questbridge.org/apply-to-college/programs/national-college-match/apply/dates-and-deadlines',
      'https://questbridge.zendesk.com/hc/en-us/articles/218776997-When-is-the-National-College-Match-application-due'
    ],
    lastChecked: '2026-08-16'
  },
  {
    id: 'jkc-college-scholarship',
    name: 'Cooke College Scholarship Program',
    provider: 'Jack Kent Cooke Foundation',
    amount: 55000,
    amountDisplay: 'Up to $55,000/year',
    amountNote: '"Last-dollar" funding after other aid — actual amount varies by student\'s cost of attendance and other aid received.',
    deadline: 'Opens Aug 19, 2026',
    deadlineNote: 'Application opens Aug 19, 2026. Exact closing date for this cycle was not published on the official page as of this check — historically mid-November (Nov 11-12 in recent cycles).',
    deadlineVerified: false,
    level: ["High school senior (entering Bachelor's)"],
    field: 'Any field',
    citizenship: ['Must reside in the U.S. or a U.S. territory and attend all 4 years of high school in the U.S.'],
    locationNote: 'Not currently open to students who attend high school outside the U.S. College itself can be anywhere, but must be an accredited 4-year institution.',
    gpaMin: 3.5,
    gpaNote: 'Sources vary between 3.5 and 3.75 minimum unweighted GPA — confirm exact figure at jkcf.org before applying.',
    gpaVerified: false,
    needBased: true,
    meritBased: true,
    incomeCapNote: 'Foundation considers applicants with family adjusted gross income up to approximately $95,000 (confirm current cap on official site).',
    requirements: ['Online application', 'Essay', 'Test scores (SAT/ACT/AP/IB)', 'References', 'Financial documentation (3 years of AGI)'],
    why: 'One of the largest need-based awards available — covers a large share of cost at top four-year colleges, plus advising through graduation.',
    applyUrl: 'https://www.jkcf.org/our-scholarships/college-scholarship-program/how-to-apply/',
    sourceUrl: 'https://www.jkcf.org/our-scholarships/college-scholarship-program/',
    sourceUrls: [
      'https://www.jkcf.org/our-scholarships/college-scholarship-program/how-to-apply/',
      'https://www.jkcf.org/our-scholarships/college-scholarship-program/faqs/'
    ],
    lastChecked: '2026-08-16'
  },
  {
    id: 'gates-scholarship',
    name: 'The Gates Scholarship',
    provider: 'Bill & Melinda Gates Foundation',
    amount: null,
    amountDisplay: 'Full remaining cost of attendance',
    amountNote: '"Last-dollar" scholarship — covers tuition, fees, books, housing, and food not already covered by other aid. Not a fixed dollar figure.',
    deadline: 'Sep 15, 2026',
    deadlineNote: 'Application opened mid-July 2026.',
    deadlineVerified: true,
    level: ["High school senior (entering Bachelor's, full-time, 4-year)"],
    field: 'Any field, at an accredited nonprofit U.S. college/university',
    citizenship: ['U.S. citizen or permanent resident'],
    locationNote: null,
    gpaMin: 3.3,
    gpaNote: 'Minimum 3.3 cumulative weighted GPA (or equivalent)',
    needBased: true,
    meritBased: true,
    ethnicityNote: 'Must identify with at least one of: African American, American Indian/Alaska Native, Asian & Pacific Islander American, and/or Hispanic American.',
    incomeCapNote: 'Must be Pell-eligible (federal financial need threshold).',
    requirements: ['Online application', 'Essays', 'Recommendations', 'FAFSA / Pell eligibility documentation'],
    why: 'Highly selective full-ride for Pell-eligible minority students — about 300 selected nationally each year.',
    applyUrl: 'https://gatesscholarships.org/',
    sourceUrl: 'https://gatesscholarships.org/',
    sourceUrls: ['https://gatesscholarships.org/'],
    lastChecked: '2026-08-16'
  },
  {
    id: 'hsf-scholar',
    name: 'HSF Scholar Program (General College Scholarship)',
    provider: 'Hispanic Scholarship Fund',
    amount: 5000,
    amountDisplay: '$500 – $5,000',
    amountNote: 'Amount depends on financial need and available funds. Not all HSF Scholars receive a scholarship award.',
    deadline: 'Feb 15, 2026 (closed)',
    deadlineNote: 'Applications typically open Jan 1 and close mid-February each year. 2027 cycle dates not yet posted as of this check — confirm at hsf.net.',
    deadlineVerified: true,
    deadlineStatus: 'closed_for_cycle',
    level: ['High school senior', 'Current undergraduate', 'Graduate student'],
    field: 'Any field (emphasis on STEM in some cycles)',
    citizenship: ['U.S. citizen, permanent legal resident, or DACA recipient'],
    locationNote: null,
    gpaMin: 3.0,
    gpaNote: 'Minimum 3.0 GPA for high school students; minimum 2.5 GPA for college/graduate students.',
    needBased: true,
    meritBased: true,
    ethnicityNote: 'Must identify as being of Hispanic heritage (open to all races within that heritage).',
    requirements: ['Online application', 'FAFSA or state-based financial aid form', 'Enrollment verification'],
    why: 'Open to a broad range of study levels and doesn\'t require a specific major — one of the largest Hispanic-serving scholarship networks in the U.S.',
    applyUrl: 'https://www.hsf.net/scholarship/',
    sourceUrl: 'https://www.hsf.net/scholarship/',
    sourceUrls: ['https://www.hsf.net/scholarship/'],
    lastChecked: '2026-08-16'
  },
  {
    id: 'uncf-general',
    name: 'UNCF General Scholarship',
    provider: 'UNCF (United Negro College Fund)',
    amount: null,
    amountDisplay: 'Varies — needs verification',
    amountNote: 'Third-party sources estimate roughly $2,500–$12,500/year, but this figure is not confirmed on UNCF\'s own program page — treat as unverified.',
    amountVerified: false,
    deadline: 'Mar 31 (annual)',
    deadlineNote: 'Recent cycle deadline reported as March 31, 2026 by secondary sources. Not independently confirmed on uncf.org at time of check — confirm exact date before applying.',
    deadlineVerified: false,
    level: ['Undergraduate', 'Graduate', 'Doctoral'],
    field: 'Any field',
    citizenship: ['Needs verification — not explicitly stated in sources reviewed'],
    locationNote: 'Must be enrolled full-time at one of UNCF\'s member HBCUs (37 institutions) or certain other eligible schools.',
    gpaMin: 2.5,
    gpaNote: 'Minimum 2.5 GPA (or GED completion)',
    needBased: true,
    meritBased: false,
    requirements: ['FAFSA with demonstrated unmet financial need', 'Full-time enrollment at a UNCF member institution', 'Good academic standing'],
    why: 'Restricted to UNCF member HBCUs — a strong match only if you\'re attending or planning to attend one of the 37 member schools.',
    applyUrl: 'https://scholarships.uncf.org/',
    sourceUrl: 'https://uncf.org/scholarships',
    sourceUrls: ['https://uncf.org/scholarships', 'https://scholarships.uncf.org/'],
    lastChecked: '2026-08-16'
  },
  {
    id: 'fulbright-us-student',
    name: 'Fulbright U.S. Student Program',
    provider: 'U.S. Department of State / IIE (Institute of International Education)',
    amount: null,
    amountDisplay: 'Airfare + living stipend (varies by country)',
    amountNote: 'Covers round-trip travel, a living stipend, and often health benefits — no single dollar figure; award value depends on the host country.',
    deadline: 'Oct 6, 2026',
    deadlineNote: '5:00 PM Eastern — national deadline for the 2027-2028 competition. Many universities set an earlier internal campus deadline (often 4-6 weeks earlier) — check with your school\'s Fulbright Program Adviser.',
    deadlineVerified: true,
    level: ['Graduating senior', 'Graduate student', 'Recent graduate (within ~7 years)'],
    field: 'All academic disciplines, including creative and performing arts',
    citizenship: ['U.S. citizen or U.S. national at time of application. Permanent residents are NOT eligible.'],
    locationNote: 'For study, research, or English teaching in one of 160+ countries abroad.',
    gpaMin: null,
    gpaNote: 'No published minimum GPA — evaluated holistically on proposal quality and academic/professional record.',
    needBased: false,
    meritBased: true,
    requirements: ['Statement of Grant Purpose', 'Personal statement', 'Letters of affiliation (for research/study awards)', 'Recommendations', 'Language evaluation (country-dependent)', 'Bachelor\'s degree conferred before grant start'],
    why: 'For students planning to study, research, or teach abroad after their degree — directly relevant if "study abroad" is part of your plan.',
    applyUrl: 'https://us.fulbrightonline.org/applicants',
    sourceUrl: 'https://us.fulbrightonline.org/about/eligibility',
    sourceUrls: [
      'https://us.fulbrightonline.org/about/eligibility',
      'https://us.fulbrightonline.org/applicants'
    ],
    lastChecked: '2026-08-16'
  },
  {
    id: 'elks-mvs',
    name: 'Elks National Foundation "Most Valuable Student" Scholarship',
    provider: 'Elks National Foundation',
    amount: 30000,
    amountDisplay: '$4,000 – $30,000 (over 4 years)',
    amountNote: '500 total awards: 2 top national awards of $30,000 (over 4 years), 480 runner-up awards of $4,000 (over 4 years). Male and female students compete separately.',
    deadline: 'Nov 12, 2026',
    deadlineNote: 'Multiple third-party sources cite Nov 12, 2026 for this cycle; the official elks.org page did not display an explicit date at time of check — confirm before applying.',
    deadlineVerified: false,
    level: ["High school senior (entering Bachelor's, full-time)"],
    field: 'Any field',
    citizenship: ['U.S. citizen'],
    locationNote: 'No Elks membership or family affiliation required. Must enroll full-time at an accredited U.S. 4-year college/university.',
    gpaMin: null,
    gpaNote: 'No published minimum GPA — judged on scholarship, leadership, and financial need combined.',
    needBased: true,
    meritBased: true,
    requirements: ['Online application', 'Essay/short-answer responses', 'Transcript', 'Recommendation'],
    why: 'Judges on leadership and community involvement as much as GPA — a good fit if your activities outweigh a top-decile transcript.',
    applyUrl: 'https://www.elks.org/scholars/scholarships/mvs.cfm',
    sourceUrl: 'https://www.elks.org/scholars/scholarships/mvs.cfm',
    sourceUrls: ['https://www.elks.org/scholars/scholarships/mvs.cfm'],
    lastChecked: '2026-08-16'
  },
  {
    id: 'swe-society-selected',
    name: 'SWE Society-Selected Scholarships (Emerging First Year / Collegiate / Graduate)',
    provider: 'Society of Women Engineers',
    amount: null,
    amountDisplay: 'Varies by named scholarship',
    amountNote: 'SWE administers dozens of individually named, endowed scholarships through one shared application; amounts differ per award and aren\'t published as a single figure.',
    deadline: 'Closed for 2026-27 cycle',
    deadlineNote: 'Official page confirms Society-Selected Scholarships (Emerging First Year, Collegiate/Graduate, India Scholars) are closed for 26-27. An interest form for the 2027-2028 cycle is open.',
    deadlineVerified: true,
    deadlineStatus: 'closed_for_cycle',
    level: ["Undergraduate (sophomore+) and graduate — Emerging First Year track covers incoming freshmen/current high school seniors"],
    field: 'Engineering, engineering technology, or computer science (ABET-accredited program)',
    citizenship: ['Needs verification — not explicitly stated as a restriction on the overview page'],
    locationNote: 'Program also runs a separate India Scholars track for eligible schools in India.',
    genderNote: 'Open only to applicants who identify as female/woman.',
    gpaMin: null,
    gpaNote: 'No single published minimum — varies by individual named scholarship.',
    needBased: false,
    meritBased: true,
    requirements: ['Single shared online application covers all eligible Society-Selected awards', 'Must not be fully funded for tuition, fees, and books'],
    why: 'One application considers you for many separate named engineering scholarships at once — currently in its off-cycle, so plan ahead for 2027-2028.',
    applyUrl: 'https://swe.org/apply-for-a-swe-scholarship/',
    sourceUrl: 'https://swe.org/scholarships-overview/',
    sourceUrls: ['https://swe.org/scholarships-overview/'],
    lastChecked: '2026-08-16'
  },
  {
    id: 'chevening-scholarship',
    name: 'Chevening Scholarship',
    provider: 'UK Government (Foreign, Commonwealth & Development Office)',
    amount: null,
    amountDisplay: 'Full tuition + monthly stipend',
    amountNote: 'Covers tuition, a monthly stipend (~£1,347–£1,690 depending on location), travel costs, an arrival/departure allowance, and one visa application — not a single fixed dollar figure.',
    deadline: 'Oct 6, 2026',
    deadlineNote: '11:00 UTC. Applications opened Aug 4, 2026. Interviews Mar–Apr 2027; results from mid-June 2027; unconditional university offer due Jul 8, 2027.',
    deadlineVerified: true,
    level: ["Graduate (one-year taught Master's in the UK)"],
    field: 'Any field, at any eligible UK university',
    citizenship: ['Citizen of a Chevening-eligible country or territory (160+) — U.K. citizens, EU/EEA nationals, and U.S. citizens are NOT eligible.'],
    locationNote: 'Must return to home country for at least 2 years after the award ends.',
    gpaMin: null,
    gpaNote: 'No published minimum GPA, but Chevening notes candidates typically hold the equivalent of a UK upper-second-class (2:1) honours degree.',
    needBased: false,
    meritBased: true,
    workExperienceNote: 'Requires at least 2,800 hours (~2 years) of work experience completed after the undergraduate degree.',
    requirements: ['Online application with 4 essays', 'References (if longlisted)', 'Applications to 3 eligible UK university courses', 'Unconditional offer from at least one by Jul 8, 2027', 'English language proficiency per chosen university'],
    why: 'Fully funded UK master\'s for emerging leaders from 160+ eligible countries — evaluates leadership and impact potential over pure academics.',
    applyUrl: 'https://www.chevening.org/apply/',
    sourceUrl: 'https://www.chevening.org/scholarships/application-timeline/',
    sourceUrls: [
      'https://www.chevening.org/scholarships/application-timeline/',
      'https://www.chevening.org/scholarships/'
    ],
    lastChecked: '2026-08-16'
  },
  {
    id: 'mbzuai-graduate-scholarship',
    name: 'MBZUAI Graduate Scholarship (MSc & PhD in AI)',
    provider: 'Mohamed bin Zayed University of Artificial Intelligence (MBZUAI)',
    amount: null,
    amountDisplay: 'Full tuition + monthly stipend',
    amountNote: 'Covers 100% tuition, a monthly stipend (~AED 15,000–15,500 for MSc, ~AED 17,500 for PhD), health insurance, and visa sponsorship. Housing support is available with cost deducted from the stipend if used. The separate Master in Applied AI (MAAI) program is fee-based and NOT covered by this scholarship.',
    deadline: 'Historically mid-Nov (priority) / mid-Dec (final)',
    deadlineNote: 'Multiple sources cite a Nov 15, 2025 priority deadline and Dec 15, 2025 final deadline for the Fall 2026 cohort — that cycle has closed. Exact dates for the next (Fall 2027) cycle were not yet published as of this check; confirm at mbzuai.ac.ae.',
    deadlineVerified: false,
    deadlineStatus: 'closed_for_cycle',
    level: ["Bachelor's degree completed (for MSc)", "Master's degree completed (for PhD)"],
    field: 'STEM fields related to AI — computer science, electrical/computer engineering, mathematics, physics, robotics',
    citizenship: ['Open to all nationalities — international students and UAE nationals/residents are both eligible.'],
    locationNote: 'Program is in Abu Dhabi, UAE; funded students are generally expected to be present on campus.',
    gpaMin: 3.2,
    gpaNote: 'Minimum cumulative GPA of 3.2/4.0 is most commonly cited, though some program pages list 3.0–3.5 depending on degree — confirm for your specific program.',
    needBased: false,
    meritBased: true,
    requirements: ['Online application', 'CV', 'Official transcripts and degree certificate', 'Statement of Purpose', 'Research Statement (PhD only)', 'English proficiency score (e.g. IELTS 6.5+ / TOEFL 90+)', '2 recommendation letters (MSc) or 3 (PhD)'],
    why: 'Funding is automatic for every admitted full-time MSc/PhD student — the competitive part is admission itself, not a separate scholarship application. Strong fit for a STEM/CS/robotics background once you\'ve completed your bachelor\'s.',
    applyUrl: 'https://mbzuai.ac.ae/study/graduate-admission-process/',
    sourceUrl: 'https://mbzuai.ac.ae/study/graduate-admission-process/',
    sourceUrls: ['https://mbzuai.ac.ae/study/graduate-admission-process/'],
    lastChecked: '2026-08-16'
  }
];
